set nocompatible

" Vundle
    filetype off
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()
    " Vundle runtime path manager
    Bundle 'gmarik/vundle'

    " Filesystem
    Bundle 'scrooloose/nerdtree'
    Bundle 'rking/ag.vim'
    Bundle 'kien/ctrlp.vim'

    " Motion
    Bundle 'goldfeld/vim-seek'
    Bundle 'Lokaltog/vim-easymotion'

    " Text manipulation
    Bundle 'scrooloose/nerdcommenter'
    Bundle 'godlygeek/tabular'
    Bundle 'tpope/vim-surround'

    " Text objects
    Bundle 'michaeljsmith/vim-indent-object'
    Bundle 'vim-scripts/argtextobj.vim'
    Bundle 'bkad/CamelCaseMotion'

    " Language-specific plugins
    Bundle 'wting/rust.vim'
    Bundle 'Twinside/vim-haskellConceal'
    Bundle 'ehamberg/vim-cute-python'
    Bundle 'pbrisbin/html-template-syntax'

    " Other
    Bundle 'bling/vim-airline'
    filetype plugin indent on


" Colours
    syntax on
    let g:solarized_termcolors = 256
    set t_Co=256
    set background=dark
    colorscheme bigbug


" Buffers instead of tabs
    nnoremap <leader>T :enew<CR>
    nnoremap gt :bnext<CR>
    nnoremap gT :bprevious<CR>
    nnoremap <leader>bQ :bp <BAR> bd #<CR>
    nnoremap <leader>bl :ls<CR>


" Airline
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#fnamemod = ':t'


" CtrlP
    let g:ctrlp_map = '<c-p>'
    let g:ctrlp_cmd = 'CtrlP'


" Tabs
    set tabstop=4
    set shiftwidth=4
    set softtabstop=4
    set expandtab


" Folding
    set foldmethod=indent
    set foldcolumn=0
    set foldnestmax=7


" Pasting
    nnoremap <leader>p :set invpaste paste?<CR>
    set showmode


" Command completion
    set wildmenu
    set wildmode=list:full
    cnoremap <C-p> <Up>
    cnoremap <C-n> <Down>
    set history=200


" Searching
    set ignorecase
    set smartcase
    set gdefault
    set incsearch
    set showmatch
    set hlsearch


" Wrapping
    set wrap
    set textwidth=110
    set formatoptions=tnq
    set colorcolumn=110


" Non-textual characters
    set list
    set listchars=tab:▸\ ,eol:¬


" No scrollbars in gvim
    if has("gui_running")
        set guioptions-=rL
        set guioptions+=a
    endif


" Shortcuts
    " Edit and source this file
    nnoremap <leader>ev :edit $MYVIMRC<CR>
    nnoremap <leader>sv :source $MYVIMRC<CR>

    " jk to enter normal mode
    inoremap jk <Esc>
    vnoremap jk <Esc>

    " Enter and backspace to add empty lines
    nnoremap <CR> o<Esc>k
    nnoremap <BS> O<Esc>j

    " Easier navigation of windows
    nnoremap <C-h> <C-w>h
    nnoremap <C-j> <C-w>j
    nnoremap <C-k> <C-w>k
    nnoremap <C-l> <C-w>l

    " Turn off search highlighting
    nnoremap <leader><Space> :noh<CR>

    " NERDTree
    nnoremap <C-n> :NERDTreeToggle<CR>

    " Tabularize
    nnoremap <leader>= :Tabularize/=<CR>
    nnoremap <leader>: :Tabularize/:\zs<CR>
    nnoremap <leader>, :Tabularize/,\zs<CR>


" Various uncategorized settings
    set encoding=utf-8
    set scrolloff=3
    set autoindent
    set showmode
    set showcmd
    set hidden
    set novisualbell
    set cursorline
    set ttyfast
    set lazyredraw
    set ruler
    set backspace=indent,eol,start
    set laststatus=2
    set cole=2
    set timeoutlen=300
    set number
    set relativenumber


" TEX: Don't conceal sub- and superscripts
    let g:tex_conceal='adgm'
