export PATH=$HOME/bin:$PATH
export WORKON_HOME=~/.virtualenvs
export RUST_SRC_PATH=/usr/src/rust/src

if [ -f /usr/lib/nvidia/libGL.so ]; then
   export LD_PRELOAD=/usr/lib/nvidia/libGL.so
fi

# for dir in \
#     ~/.cabal/bin
# ; do
#     if [[ -d $dir ]]; then path+=$dir; fi
# done
