#!/usr/bin/zsh

if [[ ! -d ~/.antigen ]]
then
   git clone https://github.com/zsh-users/antigen.git ~/.antigen
fi

source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen theme candy

antigen bundle archlinux
antigen bundle colored-man-pages
antigen bundle fasd
antigen bundle zsh-users/zsh-syntax-highlighting

export EDITOR=ecli

alias sume="sudo -E su -m"
alias sudd="sudo -E"

source $HOME/.localzshrc
