#!/usr/bin/zsh

unset GREP_OPTIONS

if [[ ! -d ~/.antigen ]]
then
   git clone https://github.com/zsh-users/antigen.git ~/.antigen
fi

source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen theme candy

antigen bundle archlinux
antigen bundle colored-man-pages
antigen bundle fasd
antigen bundle git
antigen bundle virtualenvwrapper

antigen bundle djui/alias-tips
antigen bundle Vifon/deer
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

export EDITOR=ecli

alias sume="sudo -E su -m"
alias sudd="sudo -E"

source $HOME/.localzshrc
